RPP Voxel 3D Tensor Add/Subtract scalar on HOST and HIP
ROCm/rpp pull request #272
Opened 2023-12-14 00:37 UTC by r-abishek

- Adds support for voxel 3D tensor add/subtract scalar ops on HOST and HIP
- Adds relevant QA tests / unit tests and perf tests.

2023-12-14 00:40 UTC, r-abishek commented
@kiritigowda Local Ubuntu 20.04 tests:

HOST:
![image](https://github.com/ROCm/rpp/assets/52214183/c78d5c69-c6af-4780-8540-9195dfef9007)

HIP:
![image](https://github.com/ROCm/rpp/assets/52214183/38cc2c72-f931-4585-8555-ef89a0dfeb75)

2024-01-05 19:27 UTC, rrawther commented on src/modules/hip/kernel/subtract_scalar.hpp
> +    int id_x = (hipBlockIdx_x * hipBlockDim_x + hipThreadIdx_x) * 8;        // W - inner most dim vectorized
I see that we are following a mix of camel and snake_case for variable names. Going forward, we need to follow Google coding style for newly implemented functions

2024-01-05 20:18 UTC, rrawther commented on utilities/test_suite/REFERENCE_OUTPUT_VOXEL/add_scalar/add_scalar_nifti_output_pkd3.csv
As discussed can we combine all these into a single csv file until we have a way to automatically generate the golden output

2024-01-05 20:19 UTC, rrawther requested changes
please address the review comments

2024-01-31 19:31 UTC, rrawther approved these changes

2024-02-09 23:01 UTC, merged