RPP Magnitude on HOST and HIP
ROCm/rpp pull request #278
Opened 2023-12-20 21:30 UTC by r-abishek

- Adds magnitude functionality to HOST and HIP with support for U8/F16/F32/I8 depths and NCHW/NHWC layouts.
- Adds relevant QA tests, unit tests, performance tests

2024-01-02 21:57 UTC, kiritigowda commented
@r-abishek  - need to resolve conflicts to run CI

2024-01-08 17:26 UTC, rrawther commented on src/modules/hip/kernel/magnitude.hpp
> +__device__ void magnitude_hip_compute(uchar *srcPtr, d_float8 *src1_f8, d_float8 *src2_f8, d_float8 *dst_f8)
please make them templated functions as discussed

2024-01-08 17:28 UTC, rrawther commented on utilities/test_suite/REFERENCE_OUTPUT/magnitude/magnitude_u8_Tensor_PKD3.csv
please combine all csvs into single one

2024-01-08 17:28 UTC, rrawther requested changes
please address review comments

2024-01-08 17:29 UTC, rrawther commented
@AryanSalmanpour : Can you please review the HIP kernels

2024-01-17 23:25 UTC, r-abishek commented
@kiritigowda Ubuntu 20.04 machine has no space on device left, so CI fails with that error for this PR.

2024-02-09 23:01 UTC, kiritigowda commented
@r-abishek - conflicts need to be resolved.

2024-02-13 01:42 UTC, r-abishek commented
@kiritigowda Conflicts resolved

2024-02-14 00:10 UTC, merged