RPP Tensor Audio Support - Resample
ROCm/rpp pull request #310
Opened 2024-02-21 19:35 UTC by r-abishek

- Adds Tensor Audio support on HOST for Resample
- Adds relevant QA pass/fail tests and Performance tests

2024-03-19 16:20 UTC, rrawther requested changes
Added few comments

2024-03-19 16:20 UTC, rrawther commented on src/modules/cpu/kernel/resample.hpp
> +            Rpp32s outBegin = 0;
Probably you can get rid of this line an start the loop from 0 instead

2024-03-19 16:20 UTC, rrawther commented on src/modules/cpu/kernel/resample.hpp
> +                        if (loc0 + inBlockRounded < 0)
Is this (loc0 + inBlockRounded) or loc0 - inBlockRounded ?
How can it become -ve?

2024-03-21 00:18 UTC, rrawther requested changes
please address review comments

2024-03-26 00:22 UTC, rrawther approved these changes

2024-03-28 06:41 UTC, kiritigowda commented
@r-abishek  - failing CI -- can you verify if this is a CI/PR failure?

2024-04-03 04:47 UTC, merged