RPP Tensor Audio Support - Slice
ROCm/rpp pull request #325
Opened 2024-03-15 23:42 UTC by r-abishek

This PR modifies the already added voxel slice kernels to now accept anchor and shape params for a more generic version for Audio support.

Slice can now function in all 3 test suites:
- In the audio test suite by calling it with a 1D float tensor.
- In the image test suite by calling it with 2D or 3D tensors (1 channel / 3 channel images)
- In the voxel test suite by calling it with a 4D tensor. (3 channel 3D voxel images)

- Adds support to fill the padded region with fill value when padding is enabled
- Adds test cases for slice in audio and voxel test suites
- Modifies the non-silent region kernel output types to make it compatible with latest slice.

2024-04-03 15:11 UTC, kiritigowda commented
@r-abishek - please resolve merge conflicts

2024-04-12 16:26 UTC, LakshmiKumar23 commented
@r-abishek can you resolve merge conflicts?

2024-04-13 00:08 UTC, r-abishek commented
@kiritigowda @LakshmiKumar23 All merge conflicts resolved and CI passing

2024-04-26 18:14 UTC, kiritigowda commented
@r-abishek please resolve conflicts.

2024-05-01 01:57 UTC, rrawther commented on src/modules/cpu/kernel/slice.hpp
> +                            memcpy(dstPtrRow, srcPtrRow, copyLengthInBytes);
Is this as fast as doing in AVX?

2024-05-01 01:59 UTC, rrawther requested changes
Please check if we can write a fast mem_cpy using AVX

2024-05-01 02:00 UTC, rrawther commented
@AryanSalmanpour : Can you please review the HIP kernels in this PR?

2024-05-08 00:02 UTC, rrawther approved these changes

2024-05-08 17:00 UTC, AryanSalmanpour approved these changes

2024-05-08 18:38 UTC, kiritigowda commented
@r-abishek -- needs merge conflicts resolved

2024-05-08 21:29 UTC, merged