RPP Test suite - Display all cases for "--help" request
ROCm/rpp pull request #379
Opened 2024-06-13 23:13 UTC by r-abishek

This PR adds mods to make it easier for the user and display case numbers with corresponding augmentation names when the user asks for "--help" in any of the 4 test suite scripts in RPP (image/voxel/audio/misc).

2024-06-14 01:48 UTC, r-abishek commented
Sample output:
```
python3 runTests.py --help
```
![image](https://github.com/ROCm/rpp/assets/52214183/4532e675-46e3-4851-b99c-6753a3c4dca4)

2024-06-20 21:37 UTC, rrawther requested changes
Please address the review comments

2024-06-25 00:38 UTC, r-abishek commented on utilities/test_suite/HIP/runMiscTests.py
> +    if '--help' or '-h' in sys.argv:
addressed

2024-06-26 03:23 UTC, r-abishek commented
@rrawther @kiritigowda Changes are addressed on this, could be merged

2024-06-26 06:41 UTC, kiritigowda commented
@r-abishek need merge conflicts resolved

2024-06-26 16:37 UTC, r-abishek commented
@kiritigowda resolved

2024-06-27 14:50 UTC, kiritigowda approved these changes

2024-07-10 15:47 UTC, rrawther approved these changes

2024-07-10 22:38 UTC, merged