RPP Audio Support HIP - To Decibels
ROCm/rpp pull request #398
Opened 2024-07-10 00:40 UTC by r-abishek

- Adds RPP audio support for To Decibels on HIP backend.
- Adds relevant qa tests and performance tests.

2024-07-16 00:19 UTC, rrawther requested changes
Added some comments

2024-07-16 23:38 UTC, r-abishek commented
@rrawther Rajy I think there's some GUI issue? Not seeing any comment above

2024-07-19 00:00 UTC, rrawther approved these changes

2024-07-24 06:49 UTC, kiritigowda commented
@r-abishek can you fix these merge conflicts?

2024-07-26 17:20 UTC, r-abishek commented
@kiritigowda resolved

2024-07-30 22:35 UTC, LakshmiKumar23 approved these changes
ran the python script `runAudioTests.py`

2024-08-01 21:00 UTC, merged