RPP Audio Support HIP - Spectrogram
ROCm/rpp pull request #433
Opened 2024-08-22 18:49 UTC by r-abishek

- Adds RPP audio support for Spectrogram on HIP backend.
- Adds relevant qa tests and performance tests.

2024-09-16 18:17 UTC, kiritigowda commented
@r-abishek -- merge conflicts

2024-09-19 17:25 UTC, AryanSalmanpour requested changes

2024-09-19 17:25 UTC, AryanSalmanpour commented on src/modules/hip/kernel/spectrogram.hpp
> +    CHECK_RETURN_STATUS(hipStreamSynchronize(handle.GetStream()));
Please remove `CHECK_RETURN_STATUS(hipStreamSynchronize(handle.GetStream())));` from here and line 198 and move it to after the last hipLaunchKernelGGL call.

2024-09-24 22:47 UTC, r-abishek commented
@AryanSalmanpour This PR addresses verbal comments from the code review now

2024-09-24 23:04 UTC, AryanSalmanpour approved these changes

2024-10-17 18:42 UTC, r-abishek commented
All Jenkins CI passing. Waiting on Azure - https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10403&view=results

2024-10-18 17:23 UTC, randyh62 approved these changes
Looks good to me.

2024-10-22 15:47 UTC, merged