WIP - Test suite - hip build fix
ROCm/rpp pull request #453
Opened 2024-09-19 17:19 UTC by r-abishek

- Add fix for test suite hip build

2024-09-21 17:55 UTC, kiritigowda commented
@r-abishek can you add the fix for Issue #454 here?

2024-09-23 21:57 UTC, r-abishek commented
@kiritigowda Added iomanip PR updates here - https://github.com/r-abishek/rpp/pull/344

2024-10-01 20:20 UTC, kiritigowda commented
@r-abishek any updates on this PR? Need the fix to solve test failures

2024-10-02 18:33 UTC, kiritigowda commented
@rrawther - this fix is required to pass CI -- issue mentioned -- #454

2024-10-02 18:39 UTC, rrawther commented
@r-abishek : We need to merge this PR asap as CI is failing on bunch of PRs. Is it still WIP?

2024-10-02 18:41 UTC, rrawther commented on utilities/test_suite/HIP/CMakeLists.txt
> +set(LINK_LIBRARY_LIST ${LINK_LIBRARY_LIST} OpenMP::OpenMP_CXX)
why OpenMP::OpenMP_CXX is required in link library list?

2024-10-02 18:42 UTC, rrawther requested changes
Added a comment

2024-10-02 18:57 UTC, r-abishek commented
@kiritigowda @rrawther Please see screenshots below with lsb_release -a command to show Ubuntu passing on 22.04 and 20.04:

Passing on Ubuntu 22.04:
![image](https://github.com/user-attachments/assets/ad1d18c7-1949-4195-a637-0ef8e95180db)

Passing on Ubuntu 20.04:
![image](https://github.com/user-attachments/assets/d12dc37d-ffe7-4779-a856-6311e0ea9da4)

2024-10-02 18:57 UTC, r-abishek commented
@kiritigowda @rrawther Current fails on CI are just since the right libs are not installed on the CI machine for both SLES and RHEL:

On RHEL9:
![image](https://github.com/user-attachments/assets/824d4506-e26a-4c0a-92f9-96b784d0a52c)

On SLES15:
![image](https://github.com/user-attachments/assets/467ad964-d26d-4c9d-bea1-08f01b9aa240)

2024-10-02 20:36 UTC, kiritigowda commented
@r-abishek - we are installing all the deps for CI. The failure on RHEL 8 can be verified with this fix.

2024-10-07 21:12 UTC, rrawther submitted a review, later dismissed

2024-10-08 18:01 UTC, kiritigowda approved these changes

2024-10-11 23:14 UTC, kiritigowda commented
@r-abishek - errors from this PR - http://math-ci.amd.com/job/mainline/job/precheckin/job/rpp/job/PR-453/5/pipeline-console/log?nodeId=282

```
: In file included from /opt/rocm-6.3.0-14898/share/rpp/test/HOST/Tensor_misc_host.cpp:25:
1: /opt/rocm-6.3.0-14898/share/rpp/test/HOST/../rpp_test_suite_misc.h:97:39: error: implicit instantiation of undefined template 'std::array<unsigned int, 4>'
1:                 std::array<Rpp32u, 4> roi = {0, 0, 100, 100};
1:                                       ^
1: /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/tuple:1595:45: note: template is declared here
1:   template<typename _Tp, size_t _Nm> struct array;
1:                                             ^
1: In file included from /opt/rocm-6.3.0-14898/share/rpp/test/HOST/Tensor_misc_host.cpp:25:
1: /opt/rocm-6.3.0-14898/share/rpp/test/HOST/../rpp_test_suite_misc.h:104:39: error: implicit instantiation of undefined template 'std::array<unsigned int, 6>'
1:                 std::array<Rpp32u, 6> roi = {0, 0, 0, 50, 50, 8};
1:                                       ^
1: /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/tuple:1595:45: note: template is declared here
1:   template<typename _Tp, size_t _Nm> struct array;
1:                                             ^
1: In file included from /opt/rocm-6.3.0-14898/share/rpp/test/HOST/Tensor_misc_host.cpp:25:
1: /opt/rocm-6.3.0-14898/share/rpp/test/HOST/../rpp_test_suite_misc.h:118:39: error: implicit instantiation of undefined template 'std::array<unsigned int, 4>'
1:                 std::array<Rpp32u, 4> roi = {0, 0, 1920, 1080};
1:                                       ^
1: /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/tuple:1595:45: note: template is declared here
1:   template<typename _Tp, size_t _Nm> struct array;
1:                                             ^
1: In file included from /opt/rocm-6.3.0-14898/share/rpp/test/HOST/Tensor_misc_host.cpp:25:
1: /opt/rocm-6.3.0-14898/share/rpp/test/HOST/../rpp_test_suite_misc.h:125:39: error: implicit instantiation of undefined template 'std::array<unsigned int, 6>'
1:                 std::array<Rpp32u, 6> roi = {0, 0, 0, 1920, 1080, 3};
1:                                       ^
1: /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/tuple:1595:45: note: template is declared here
1:   template<typename _Tp, size_t _Nm> struct array;
1:                                             ^
1: In file included from /opt/rocm-6.3.0-14898/share/rpp/test/HOST/Tensor_misc_host.cpp:25:
1: /opt/rocm-6.3.0-14898/share/rpp/test/HOST/../rpp_test_suite_misc.h:132:39: error: implicit instantiation of undefined template 'std::array<unsigned int, 8>'
1:                 std::array<Rpp32u, 8> roi = {0, 0, 0, 0, 1, 128, 128, 128};
1:                                       ^
1: /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/tuple:1595:45: note: template is declared here
1:   template<typename _Tp, size_t _Nm> struct array;
1:                                             ^
1: 5 errors generated.
1: make[3]: *** [CMakeFiles/Tensor_misc_host.dir/build.make:76: CMakeFiles/Tensor_misc_host.dir/Tensor_misc_host.cpp.o] Error 1
1: make[3]: Leaving directory '/var/jenkins_home/workspace/mainline_precheckin_rpp_PR-453/govcksC4S/rpp/build/release/utilities/test_suite/build'
1: make[2]: *** [CMakeFiles/Makefile2:119: CMakeFiles/Tensor_misc_host.dir/all] Error 2
1: make[2]: *** Waiting for unfinished jobs....
```

Check full report - http://math-ci.amd.com/job/mainline/job/precheckin/job/rpp/job/PR-453/5/pipeline-console/?selected-node=279

2024-10-12 20:13 UTC, r-abishek commented
@kiritigowda All Jenkins CI passing now for this PR - Ubuntu/SLES/RHEL.
Strict checks introduced in CMake for all packages necessary to build and run each of the 4 test sets.
PR description changed to point to all issues it addresses.

2024-10-16 16:20 UTC, r-abishek commented
@kiritigowda @rrawther Last commit is really taking too long to run the CI.

Please see CI passing on the second last commit.
![image](https://github.com/user-attachments/assets/8b98ca76-6dff-4323-b8ba-e1bc450ddf7d)

2024-10-16 17:17 UTC, kiritigowda commented
Merge pending - http://math-ci.amd.com/job/mainline/job/precheckin/job/rpp/job/PR-453/16/pipeline-graph/

2024-10-16 21:13 UTC, r-abishek commented
> Merge pending - http://math-ci.amd.com/job/mainline/job/precheckin/job/rpp/job/PR-453/16/pipeline-graph/

@kiritigowda The Ubuntu22+gfx90a may not finish since:
![image](https://github.com/user-attachments/assets/828881f7-59d4-458d-8a3d-6925fc937913)

2024-10-16 21:46 UTC, r-abishek commented
@kiritigowda All 13 CI passing now

2024-10-16 22:05 UTC, merged