RPP Rain augmentation on HOST and HIP
ROCm/rpp pull request #463
Opened 2024-10-23 05:45 UTC by r-abishek

- Updates version to RPP 1.9.5
- Adds a dash-cam rain augmentation on HOST and HIP
- Adds support for U8/F16/F32/I8 bit depths with NCHW/NHWC tensor support
- Adds relevant unit/perf tests

2024-11-15 23:24 UTC, rrawther commented on utilities/test_suite/HIP/runTests.py
> -nonQACaseList = ['6', '8', '24', '54', '84'] # Add cases present in supportedCaseList, but without QA support
does this also has precision difference? why is this not added for QA?

2024-11-15 23:25 UTC, rrawther commented on utilities/test_suite/HOST/Tensor_host.cpp
> -    bool randomOutputCase = (testCase == 6 || testCase == 8 || testCase == 84);
I have commented many times before. We should not use numbers for test cases. It is better to use ENUMs here

2024-11-15 23:25 UTC, rrawther commented on utilities/test_suite/HOST/runTests.py
> -supportedCaseList = ['0', '1', '2', '4', '5', '6', '8', '13', '20', '21', '23', '26', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '45', '46', '49', '54', '61', '63', '65', '68',
same as before. Need to change numbers to ENUMs

2024-11-15 23:26 UTC, rrawther commented on utilities/test_suite/rpp_test_suite_common.h
> +}
please revert this file as there seems to be no change

2024-12-02 17:08 UTC, spolifroni-amd requested changes

2024-12-02 17:08 UTC, spolifroni-amd commented on CHANGELOG.md
> +### Changes
```suggestion
### Changed
```

2024-12-02 17:08 UTC, spolifroni-amd commented on CHANGELOG.md
> +
Is this also unreleased? Because 1.9.8 is unreleased.

2024-12-10 04:14 UTC, kiritigowda commented
@r-abishek - needs conflicts resolved

2025-01-03 00:12 UTC, rrawther commented on utilities/test_suite/HIP/Tensor_hip.cpp
>      if(testCase == 28)
we should use ENUM for test case instead of hardcoded values for better code readability

2025-01-06 23:33 UTC, r-abishek commented on utilities/test_suite/HOST/Tensor_host.cpp
> -    bool randomOutputCase = (testCase == 6 || testCase == 8 || testCase == 84);
Addressed with #499

2025-01-06 23:33 UTC, r-abishek commented on utilities/test_suite/HOST/runTests.py
> -supportedCaseList = ['0', '1', '2', '4', '5', '6', '8', '13', '20', '21', '23', '26', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '45', '46', '49', '54', '61', '63', '65', '68',
Addressed with #499

2025-01-06 23:33 UTC, r-abishek commented on utilities/test_suite/HIP/Tensor_hip.cpp
>      if(testCase == 28)
Addressed with #499

2025-01-06 23:35 UTC, r-abishek commented on utilities/test_suite/HIP/runTests.py
> -nonQACaseList = ['6', '8', '24', '54', '84'] # Add cases present in supportedCaseList, but without QA support
These are functions that involve random rain/fog/snow/noise that don't have the pixel-wise match test.

2025-01-07 18:51 UTC, rrawther approved these changes

2025-01-08 18:11 UTC, spolifroni-amd approved these changes
The points in the changed section need to be changed so they have more info (what was it before; what is it now; what, if anything, does the user need to do)

But I don't want to hold up the review process so I'll OK this as is and we can change it later.

2025-01-13 20:24 UTC, kiritigowda commented
@r-abishek can you look at the conflicts

2025-01-14 21:57 UTC, r-abishek commented
@kiritigowda Could we merge this PR? 
Conflicts resolved, Azure passing.

2025-01-15 01:27 UTC, merged